# Generated by Django 5.1.1 on 2024-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=120)),
                ('description_produit', models.TextField()),
                ('type_produit', models.CharField(max_length=120)),
                ('quantite_actuelle', models.IntegerField()),
                ('seuil_minimum', models.IntegerField()),
            ],
        ),
    ]
